/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Tags.graphql
 * @generated SignedSource<<b0677368ef67fe6ae14c1a9f5231baa0>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Tags = {|
  +tags: ?$ReadOnlyArray<?any>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Tags",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "tags",
      "storageKey": null
    }
  ],
  "type": "Tagged"
};

module.exports = fragment;
