/**
 * This file was generated by:
 *   compile.js
 *
 * @providesModule Tags.graphql
 * @generated SignedSource<<ccbdc409c611de192c23b8329c936f9a>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Tags = {|
  +tags: $ReadOnlyArray<any>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Tags",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "tags",
      "storageKey": null
    }
  ],
  "type": "Tagged"
};

module.exports = fragment;
