// flow-typed signature: 9cdb5001200566279c14804cd1a91adf
// flow-typed version: <<STUB>>/ansi-colors_v*/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ansi-colors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ansi-colors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ansi-colors/symbols' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ansi-colors/index' {
  declare module.exports: $Exports<'ansi-colors'>;
}
declare module 'ansi-colors/index.js' {
  declare module.exports: $Exports<'ansi-colors'>;
}
declare module 'ansi-colors/symbols.js' {
  declare module.exports: $Exports<'ansi-colors/symbols'>;
}
