// flow-typed signature: 47d7da7907273ea1a1803bb10f0626fc
// flow-typed version: <<STUB>>/gulp-spawn-mocha_v*/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-spawn-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-spawn-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-spawn-mocha/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-spawn-mocha/lib/index' {
  declare module.exports: any;
}

declare module 'gulp-spawn-mocha/test/index.test' {
  declare module.exports: any;
}

declare module 'gulp-spawn-mocha/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-spawn-mocha/gulpfile.js' {
  declare module.exports: $Exports<'gulp-spawn-mocha/gulpfile'>;
}
declare module 'gulp-spawn-mocha/lib/index.js' {
  declare module.exports: $Exports<'gulp-spawn-mocha/lib/index'>;
}
declare module 'gulp-spawn-mocha/test/index.test.js' {
  declare module.exports: $Exports<'gulp-spawn-mocha/test/index.test'>;
}
declare module 'gulp-spawn-mocha/test/setup.js' {
  declare module.exports: $Exports<'gulp-spawn-mocha/test/setup'>;
}
