// flow-typed signature: abc02f3f2f7d3000fb787741d683ff90
// flow-typed version: <<STUB>>/http-proxy_v*/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-proxy/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'http-proxy/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'http-proxy/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy/common' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy/index' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy/passes/web-incoming' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy/passes/web-outgoing' {
  declare module.exports: any;
}

declare module 'http-proxy/lib/http-proxy/passes/ws-incoming' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-proxy/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'http-proxy/coverage/lcov-report/block-navigation'>;
}
declare module 'http-proxy/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'http-proxy/coverage/lcov-report/prettify'>;
}
declare module 'http-proxy/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'http-proxy/coverage/lcov-report/sorter'>;
}
declare module 'http-proxy/index' {
  declare module.exports: $Exports<'http-proxy'>;
}
declare module 'http-proxy/index.js' {
  declare module.exports: $Exports<'http-proxy'>;
}
declare module 'http-proxy/lib/http-proxy.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy'>;
}
declare module 'http-proxy/lib/http-proxy/common.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy/common'>;
}
declare module 'http-proxy/lib/http-proxy/index.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy/index'>;
}
declare module 'http-proxy/lib/http-proxy/passes/web-incoming.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy/passes/web-incoming'>;
}
declare module 'http-proxy/lib/http-proxy/passes/web-outgoing.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy/passes/web-outgoing'>;
}
declare module 'http-proxy/lib/http-proxy/passes/ws-incoming.js' {
  declare module.exports: $Exports<'http-proxy/lib/http-proxy/passes/ws-incoming'>;
}
