// flow-typed signature: 1728b47ef93a4b2d92f36d5e9baef8da
// flow-typed version: <<STUB>>/isomorphic-fetch_v*/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-fetch/fetch-bower' {
  declare module.exports: any;
}

declare module 'isomorphic-fetch/fetch-npm-browserify' {
  declare module.exports: any;
}

declare module 'isomorphic-fetch/fetch-npm-node' {
  declare module.exports: any;
}

declare module 'isomorphic-fetch/test/api.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-fetch/fetch-bower.js' {
  declare module.exports: $Exports<'isomorphic-fetch/fetch-bower'>;
}
declare module 'isomorphic-fetch/fetch-npm-browserify.js' {
  declare module.exports: $Exports<'isomorphic-fetch/fetch-npm-browserify'>;
}
declare module 'isomorphic-fetch/fetch-npm-node.js' {
  declare module.exports: $Exports<'isomorphic-fetch/fetch-npm-node'>;
}
declare module 'isomorphic-fetch/test/api.test.js' {
  declare module.exports: $Exports<'isomorphic-fetch/test/api.test'>;
}
