// flow-typed signature: fc17420e08d8db08e531519ef8089ef9
// flow-typed version: <<STUB>>/memcached_v*/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memcached'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memcached' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memcached/benchmarks/benchmark' {
  declare module.exports: any;
}

declare module 'memcached/examples/cluster_memcached_connect' {
  declare module.exports: any;
}

declare module 'memcached/examples/consistent_hashing' {
  declare module.exports: any;
}

declare module 'memcached/examples/memcached_connect_socket' {
  declare module.exports: any;
}

declare module 'memcached/examples/memcached_connect' {
  declare module.exports: any;
}

declare module 'memcached/examples/memcached_global_config' {
  declare module.exports: any;
}

declare module 'memcached/examples/memcached_local_config' {
  declare module.exports: any;
}

declare module 'memcached/examples/queue_limit' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_cachedump' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_cas' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_decr' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_delete' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_events' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_flush' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_get_binary' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_get_compression' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_get_json' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_get_largefile' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_get' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_getmulti' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_gets' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_incr' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_items' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_metaData' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_redundancy' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_set_binary' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_set_compression' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_set_json' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_set_largefile' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_set' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_settings' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_slabs' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_stats' {
  declare module.exports: any;
}

declare module 'memcached/examples/simple_version' {
  declare module.exports: any;
}

declare module 'memcached/issues/1/index' {
  declare module.exports: any;
}

declare module 'memcached/lib/connection' {
  declare module.exports: any;
}

declare module 'memcached/lib/memcached' {
  declare module.exports: any;
}

declare module 'memcached/lib/utils' {
  declare module.exports: any;
}

declare module 'memcached/test/common' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-add.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-cas.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-connections.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-get-set.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-incr-decr.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-namespace.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-parser.test' {
  declare module.exports: any;
}

declare module 'memcached/test/memcached-touch.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memcached/benchmarks/benchmark.js' {
  declare module.exports: $Exports<'memcached/benchmarks/benchmark'>;
}
declare module 'memcached/examples/cluster_memcached_connect.js' {
  declare module.exports: $Exports<'memcached/examples/cluster_memcached_connect'>;
}
declare module 'memcached/examples/consistent_hashing.js' {
  declare module.exports: $Exports<'memcached/examples/consistent_hashing'>;
}
declare module 'memcached/examples/memcached_connect_socket.js' {
  declare module.exports: $Exports<'memcached/examples/memcached_connect_socket'>;
}
declare module 'memcached/examples/memcached_connect.js' {
  declare module.exports: $Exports<'memcached/examples/memcached_connect'>;
}
declare module 'memcached/examples/memcached_global_config.js' {
  declare module.exports: $Exports<'memcached/examples/memcached_global_config'>;
}
declare module 'memcached/examples/memcached_local_config.js' {
  declare module.exports: $Exports<'memcached/examples/memcached_local_config'>;
}
declare module 'memcached/examples/queue_limit.js' {
  declare module.exports: $Exports<'memcached/examples/queue_limit'>;
}
declare module 'memcached/examples/simple_cachedump.js' {
  declare module.exports: $Exports<'memcached/examples/simple_cachedump'>;
}
declare module 'memcached/examples/simple_cas.js' {
  declare module.exports: $Exports<'memcached/examples/simple_cas'>;
}
declare module 'memcached/examples/simple_decr.js' {
  declare module.exports: $Exports<'memcached/examples/simple_decr'>;
}
declare module 'memcached/examples/simple_delete.js' {
  declare module.exports: $Exports<'memcached/examples/simple_delete'>;
}
declare module 'memcached/examples/simple_events.js' {
  declare module.exports: $Exports<'memcached/examples/simple_events'>;
}
declare module 'memcached/examples/simple_flush.js' {
  declare module.exports: $Exports<'memcached/examples/simple_flush'>;
}
declare module 'memcached/examples/simple_get_binary.js' {
  declare module.exports: $Exports<'memcached/examples/simple_get_binary'>;
}
declare module 'memcached/examples/simple_get_compression.js' {
  declare module.exports: $Exports<'memcached/examples/simple_get_compression'>;
}
declare module 'memcached/examples/simple_get_json.js' {
  declare module.exports: $Exports<'memcached/examples/simple_get_json'>;
}
declare module 'memcached/examples/simple_get_largefile.js' {
  declare module.exports: $Exports<'memcached/examples/simple_get_largefile'>;
}
declare module 'memcached/examples/simple_get.js' {
  declare module.exports: $Exports<'memcached/examples/simple_get'>;
}
declare module 'memcached/examples/simple_getmulti.js' {
  declare module.exports: $Exports<'memcached/examples/simple_getmulti'>;
}
declare module 'memcached/examples/simple_gets.js' {
  declare module.exports: $Exports<'memcached/examples/simple_gets'>;
}
declare module 'memcached/examples/simple_incr.js' {
  declare module.exports: $Exports<'memcached/examples/simple_incr'>;
}
declare module 'memcached/examples/simple_items.js' {
  declare module.exports: $Exports<'memcached/examples/simple_items'>;
}
declare module 'memcached/examples/simple_metaData.js' {
  declare module.exports: $Exports<'memcached/examples/simple_metaData'>;
}
declare module 'memcached/examples/simple_redundancy.js' {
  declare module.exports: $Exports<'memcached/examples/simple_redundancy'>;
}
declare module 'memcached/examples/simple_set_binary.js' {
  declare module.exports: $Exports<'memcached/examples/simple_set_binary'>;
}
declare module 'memcached/examples/simple_set_compression.js' {
  declare module.exports: $Exports<'memcached/examples/simple_set_compression'>;
}
declare module 'memcached/examples/simple_set_json.js' {
  declare module.exports: $Exports<'memcached/examples/simple_set_json'>;
}
declare module 'memcached/examples/simple_set_largefile.js' {
  declare module.exports: $Exports<'memcached/examples/simple_set_largefile'>;
}
declare module 'memcached/examples/simple_set.js' {
  declare module.exports: $Exports<'memcached/examples/simple_set'>;
}
declare module 'memcached/examples/simple_settings.js' {
  declare module.exports: $Exports<'memcached/examples/simple_settings'>;
}
declare module 'memcached/examples/simple_slabs.js' {
  declare module.exports: $Exports<'memcached/examples/simple_slabs'>;
}
declare module 'memcached/examples/simple_stats.js' {
  declare module.exports: $Exports<'memcached/examples/simple_stats'>;
}
declare module 'memcached/examples/simple_version.js' {
  declare module.exports: $Exports<'memcached/examples/simple_version'>;
}
declare module 'memcached/index' {
  declare module.exports: $Exports<'memcached'>;
}
declare module 'memcached/index.js' {
  declare module.exports: $Exports<'memcached'>;
}
declare module 'memcached/issues/1/index.js' {
  declare module.exports: $Exports<'memcached/issues/1/index'>;
}
declare module 'memcached/lib/connection.js' {
  declare module.exports: $Exports<'memcached/lib/connection'>;
}
declare module 'memcached/lib/memcached.js' {
  declare module.exports: $Exports<'memcached/lib/memcached'>;
}
declare module 'memcached/lib/utils.js' {
  declare module.exports: $Exports<'memcached/lib/utils'>;
}
declare module 'memcached/test/common.js' {
  declare module.exports: $Exports<'memcached/test/common'>;
}
declare module 'memcached/test/memcached-add.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-add.test'>;
}
declare module 'memcached/test/memcached-cas.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-cas.test'>;
}
declare module 'memcached/test/memcached-connections.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-connections.test'>;
}
declare module 'memcached/test/memcached-get-set.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-get-set.test'>;
}
declare module 'memcached/test/memcached-incr-decr.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-incr-decr.test'>;
}
declare module 'memcached/test/memcached-namespace.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-namespace.test'>;
}
declare module 'memcached/test/memcached-parser.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-parser.test'>;
}
declare module 'memcached/test/memcached-touch.test.js' {
  declare module.exports: $Exports<'memcached/test/memcached-touch.test'>;
}
