// flow-typed signature: 304114cdb1f317d91f7094446ce84f7f
// flow-typed version: <<STUB>>/plugin-error_v*/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plugin-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plugin-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'plugin-error/index' {
  declare module.exports: $Exports<'plugin-error'>;
}
declare module 'plugin-error/index.js' {
  declare module.exports: $Exports<'plugin-error'>;
}
