// flow-typed signature: 6f8c78aa360f4e38ac564426cd2e0058
// flow-typed version: <<STUB>>/universal-router_v*/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-router/browser' {
  declare module.exports: any;
}

declare module 'universal-router/generateUrls/browser' {
  declare module.exports: any;
}

declare module 'universal-router/generateUrls/legacy' {
  declare module.exports: any;
}

declare module 'universal-router/generateUrls/main' {
  declare module.exports: any;
}

declare module 'universal-router/legacy' {
  declare module.exports: any;
}

declare module 'universal-router/main' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router-generate-urls' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router-generate-urls.min' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-router/browser.js' {
  declare module.exports: $Exports<'universal-router/browser'>;
}
declare module 'universal-router/generateUrls/browser.js' {
  declare module.exports: $Exports<'universal-router/generateUrls/browser'>;
}
declare module 'universal-router/generateUrls/legacy.js' {
  declare module.exports: $Exports<'universal-router/generateUrls/legacy'>;
}
declare module 'universal-router/generateUrls/main.js' {
  declare module.exports: $Exports<'universal-router/generateUrls/main'>;
}
declare module 'universal-router/legacy.js' {
  declare module.exports: $Exports<'universal-router/legacy'>;
}
declare module 'universal-router/main.js' {
  declare module.exports: $Exports<'universal-router/main'>;
}
declare module 'universal-router/universal-router-generate-urls.js' {
  declare module.exports: $Exports<'universal-router/universal-router-generate-urls'>;
}
declare module 'universal-router/universal-router-generate-urls.min.js' {
  declare module.exports: $Exports<'universal-router/universal-router-generate-urls.min'>;
}
declare module 'universal-router/universal-router.js' {
  declare module.exports: $Exports<'universal-router/universal-router'>;
}
declare module 'universal-router/universal-router.min.js' {
  declare module.exports: $Exports<'universal-router/universal-router.min'>;
}
