// flow-typed signature: e4682f394bc8085b6ae43390f4e7b71a
// flow-typed version: <<STUB>>/unpack-content_v*/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unpack-content'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unpack-content' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unpack-content/dist/__mocks__/sinon' {
  declare module.exports: any;
}

declare module 'unpack-content/dist/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'unpack-content/dist/index' {
  declare module.exports: any;
}

declare module 'unpack-content/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'unpack-content/mocha/bootstrap' {
  declare module.exports: any;
}

declare module 'unpack-content/mocha/watch-reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unpack-content/dist/__mocks__/sinon.js' {
  declare module.exports: $Exports<'unpack-content/dist/__mocks__/sinon'>;
}
declare module 'unpack-content/dist/__tests__/index-test.js' {
  declare module.exports: $Exports<'unpack-content/dist/__tests__/index-test'>;
}
declare module 'unpack-content/dist/index.js' {
  declare module.exports: $Exports<'unpack-content/dist/index'>;
}
declare module 'unpack-content/gulpfile.babel.js' {
  declare module.exports: $Exports<'unpack-content/gulpfile.babel'>;
}
declare module 'unpack-content/mocha/bootstrap.js' {
  declare module.exports: $Exports<'unpack-content/mocha/bootstrap'>;
}
declare module 'unpack-content/mocha/watch-reporter.js' {
  declare module.exports: $Exports<'unpack-content/mocha/watch-reporter'>;
}
