#!/usr/bin/env ruby

# Helper script. Relies on a number of artifacts.
#
# Usage:
#
#   git filter-branch -f --index-filter true --parent-filter ~/bin/import-filter HEAD
#

require 'json'
require 'shellwords'

$stderr.puts ENV['PWD']
plan = JSON[File.read(ENV['HOME'] + '/bin/legacy-plan.json')]

def escape(string)
  Shellwords.shellescape(string)
end

def markdownify(commit)
  [
    '---',
    "title: #{commit['title']}",
    '---',
    '',
    commit['markdown'],
  ].join("\n") + "\n"
end

def log(message)
  $stderr.puts(message)
end

rewriting = ENV['GIT_COMMIT']
match = $stdin.read.chomp.match(/^\s*-p\s+([0-9a-f]{40})$/)
if match
  base = %x{git rev-parse #{rewriting}^}.chomp
  parent = escape(match[1])
  info = plan[rewriting]
  if info && !info.empty?
    info.each do |commit|
      # Get parent commit tree and load it into the index.
      %x{git read-tree #{parent}}

      # Get the new file into the object database.
      markdown = markdownify(commit)
      hash = nil
      IO.popen(%w[git hash-object -w --stdin], 'w+') do |pipe|
        pipe.write markdown
        pipe.close_write
        hash = pipe.read.chomp
      end

      # Update the index with the new file.
      cacheinfo = escape("100644,#{hash},#{commit['file']}.md")
      %x{git update-index --add --cacheinfo #{cacheinfo}}

      # Create a tree object from the current index.
      tree = %x{git write-tree}.chomp

      # Create a commit object.
      message = escape("Import #{commit['file']}.md")
      date = escape(commit['posted'])
      parent = %x{GIT_AUTHOR_DATE=#{date} GIT_COMMITTER_DATE=#{date} git commit-tree -p #{parent} -m #{message} #{tree}}.chomp

      # Prep the index so that filter-branch can take over and make a commit
      # (it is going to do write-tree from current index, then commit-tree).
      %x{git read-tree -i --aggressive -m #{base} #{parent} #{rewriting}}
    end
  else
    # Nothing to insert, but we want to make sure our previously inserted stuff
    # carries forward into the index.
    if base == parent
      # Nothing to do, will only happen at the start of the rewrite.
    else
      %x{git read-tree -i --aggressive -m #{base} #{parent} #{rewriting}}
    end
  end
  puts " -p #{parent}"
else
  # This is the root commit.
end
