/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ArticlesIndex.graphql
 * @generated SignedSource<<8e7d27360b6395b99ee1ed261b5db5dc>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ArticlesIndex = {
  articles?: ?ArticlesIndex_articles;
};

export type ArticlesIndex_articles_edges_node = {
  id: string;
};

export type ArticlesIndex_articles_edges = {
  node?: ?ArticlesIndex_articles_edges_node;
};

export type ArticlesIndex_articles_pageInfo = {
  endCursor?: ?string;
  hasNextPage: boolean;
};

export type ArticlesIndex_articles = {
  edges?: ?Array<?ArticlesIndex_articles_edges>;
  pageInfo: ArticlesIndex_articles_pageInfo;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    },
    {
      "kind": "RootArgument",
      "name": "cursor",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": "cursor",
        "direction": "forward",
        "path": [
          "articles"
        ]
      }
    ]
  },
  "name": "ArticlesIndex",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "articles",
      "args": null,
      "concreteType": "ArticleConnection",
      "name": "__ArticlesIndex_articles_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "ArticleEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Article",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "FragmentSpread",
                  "name": "ArticlePreview_article",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PageInfo",
          "name": "pageInfo",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "endCursor",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "hasNextPage",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Root"
};

module.exports = fragment;
