/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PostsIndex.graphql
 * @generated SignedSource<<e487eba207fe425041cd8774b6691f52>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PostsIndex = {
  posts?: ?PostsIndex_posts;
};

export type PostsIndex_posts_edges_node = {
  id: string;
};

export type PostsIndex_posts_edges = {
  node?: ?PostsIndex_posts_edges_node;
};

export type PostsIndex_posts_pageInfo = {
  endCursor?: ?string;
  hasNextPage: boolean;
};

export type PostsIndex_posts = {
  edges?: ?Array<?PostsIndex_posts_edges>;
  pageInfo: PostsIndex_posts_pageInfo;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "RootArgument",
      "name": "count",
      "type": "Int"
    },
    {
      "kind": "RootArgument",
      "name": "cursor",
      "type": "String"
    }
  ],
  "kind": "Fragment",
  "metadata": {
    "connection": [
      {
        "count": "count",
        "cursor": "cursor",
        "direction": "forward",
        "path": [
          "posts"
        ]
      }
    ]
  },
  "name": "PostsIndex",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": "posts",
      "args": null,
      "concreteType": "PostConnection",
      "name": "__PostsIndex_posts_connection",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PostEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Post",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "FragmentSpread",
                  "name": "Post",
                  "args": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        },
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "PageInfo",
          "name": "pageInfo",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "endCursor",
              "storageKey": null
            },
            {
              "kind": "ScalarField",
              "alias": null,
              "args": null,
              "name": "hasNextPage",
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Root"
};

module.exports = fragment;
