/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule TagPreview.graphql
 * @generated SignedSource<<48e627c4aa9bffa78a0ce55e2c08ffb8>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type TagPreview = {|
  +count: ?number;
  +name: any;
  +url: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "TagPreview",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "count",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "url",
      "storageKey": null
    }
  ],
  "type": "Tag"
};

module.exports = fragment;
