#!/bin/sh

# Tag content deployments with a timestamp.

error() {
  echo "error [pre-push]: $@"
}

if [ "$1" != "content" ]; then
  exit 0
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
CONTENT_REF=refs/heads/content

INSTALLED_HOOK="$(git rev-parse --git-common-dir)/hooks/pre-push"
MAIN_WORKTREE_INFO=$(git worktree list --porcelain | head -1)
MAIN_WORKTREE_HOOK="${MAIN_WORKTREE_INFO/#worktree /}/hooks/pre-push"
HOOK_FINGERPRINT=$(shasum -a 512 "$INSTALLED_HOOK" | awk '{ print $1 }')
REPO_FINGERPRINT=$(shasum -a 512 "$MAIN_WORKTREE_HOOK" | awk '{ print $1 }')

if [ "$HOOK_FINGERPRINT" != "$REPO_FINGERPRINT" ]; then
  error "installed hook does not match repo copy"
  error "freshen with scripts/set-up-hooks or use --no-verify to force"
  exit 1
fi

while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA
do
  if [ "$LOCAL_REF" = "$CONTENT_REF" -a "$REMOTE_REF" = "$CONTENT_REF" ]; then
    git tag "$TIMESTAMP"
  fi
done
