#!/bin/sh

# Tag content deployments with a timestamp.

error() {
  echo "error [pre-push]: $@"
}

if [ "$1" != "content" ]; then
  exit 0
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
CONTENT_REF=refs/heads/content

HOOK="$(git rev-parse --git-dir)/hooks/pre-push"
HOOK_FINGERPRINT=$(shasum -a 512 "$HOOK" | awk '{ print $1 }')
REPO_FINGERPINT=$(shasum -a 512 hooks/pre-push | awk '{ print $1 }')

if [ "$HOOK_FINGERPRINT" != "$REPO_FINGERPINT" ]; then
  error "installed hook does not match repo copy"
  error "freshen with scripts/set-up-hooks or use --no-verify to force"
  exit 1
fi

while read LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA
do
  if [ "$LOCAL_REF" = "$CONTENT_REF" -a "$REMOTE_REF" = "$CONTENT_REF" ]; then
    git tag "$TIMESTAMP"
  fi
done
