import {describe, expect, it} from '@jest/globals';

import definition from '../definition';

describe('definition', () => {
  it('is a transition table containing the state machine for the lexer', () => {
    expect(definition).toEqual({
      acceptStates: new Set([
        1, 2, 3, 4, 34, 27, 51, 6, 7, 8, 9, 10, 13, 39, 41, 14, 38, 15, 16, 17,
        18, 19, 20, 21, 32, 42, 46, 50, 54, 55, 56, 22, 33, 23, 24, 25,
      ]),
      startStates: new Set([0]),
      transitions: [
        /* 0 */ new Map([
          ['Atom:\t', new Set([1])],
          ['Atom:\n', new Set([2])],
          ['Atom:\r', new Set([3])],
          ['Atom: ', new Set([1])],
          ['Atom:!', new Set([4])],
          ['Atom:"', new Set([5])],
          ['Atom:#', new Set([6])],
          ['Atom:$', new Set([7])],
          ['Atom:&', new Set([8])],
          ['Atom:(', new Set([9])],
          ['Atom:)', new Set([10])],
          ['Atom:,', new Set([2])],
          ['Atom:-', new Set([11])],
          ['Atom:.', new Set([12])],
          ['Atom:0', new Set([13])],
          ['Range:1-9', new Set([14])],
          ['Atom::', new Set([15])],
          ['Atom:=', new Set([16])],
          ['Atom:@', new Set([17])],
          ['Range:A-Z', new Set([18])],
          ['Atom:[', new Set([19])],
          ['Atom:]', new Set([20])],
          ['Atom:_', new Set([18])],
          ['Range:a-e', new Set([18])],
          ['Atom:f', new Set([21])],
          ['Range:g-n', new Set([18])],
          ['Atom:o', new Set([22])],
          ['Range:p-z', new Set([18])],
          ['Atom:{', new Set([23])],
          ['Atom:|', new Set([24])],
          ['Atom:}', new Set([25])],
          ['Atom:\ufeff', new Set([2])],
        ]),
        /* 1 */ new Map([
          ['Atom:\t', new Set([1])],
          ['Atom: ', new Set([1])],
        ]),
        /* 2 */ new Map(),
        /* 3 */ new Map([['Atom:\n', new Set([2])]]),
        /* 4 */ new Map(),
        /* 5 */ new Map([
          ['Atom:\t', new Set([26])],
          ['Range: -!', new Set([26])],
          ['Atom:"', new Set([27])],
          ['Range:#-[', new Set([26])],
          ['Atom:\\', new Set([28])],
          ['Range:]-\uffff', new Set([26])],
        ]),
        /* 6 */ new Map([
          ['Atom:\t', new Set([6])],
          ['Range: -\uffff', new Set([6])],
        ]),
        /* 7 */ new Map(),
        /* 8 */ new Map(),
        /* 9 */ new Map(),
        /* 10 */ new Map(),
        /* 11 */ new Map([
          ['Atom:0', new Set([13])],
          ['Range:1-9', new Set([14])],
        ]),
        /* 12 */ new Map([['Atom:.', new Set([29])]]),
        /* 13 */ new Map([
          ['Atom:.', new Set([30])],
          ['Atom:E', new Set([31])],
          ['Atom:e', new Set([31])],
        ]),
        /* 14 */ new Map([
          ['Atom:.', new Set([30])],
          ['Range:0-9', new Set([14])],
          ['Atom:E', new Set([31])],
          ['Atom:e', new Set([31])],
        ]),
        /* 15 */ new Map(),
        /* 16 */ new Map(),
        /* 17 */ new Map(),
        /* 18 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-z', new Set([18])],
        ]),
        /* 19 */ new Map(),
        /* 20 */ new Map(),
        /* 21 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-q', new Set([18])],
          ['Atom:r', new Set([32])],
          ['Range:s-z', new Set([18])],
        ]),
        /* 22 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-m', new Set([18])],
          ['Atom:n', new Set([33])],
          ['Range:o-z', new Set([18])],
        ]),
        /* 23 */ new Map(),
        /* 24 */ new Map(),
        /* 25 */ new Map(),
        /* 26 */ new Map([
          ['Atom:\t', new Set([26])],
          ['Range: -!', new Set([26])],
          ['Atom:"', new Set([34])],
          ['Range:#-[', new Set([26])],
          ['Atom:\\', new Set([28])],
          ['Range:]-\uffff', new Set([26])],
        ]),
        /* 27 */ new Map([['Atom:"', new Set([35])]]),
        /* 28 */ new Map([
          ['Atom:"', new Set([26])],
          ['Atom:/', new Set([26])],
          ['Atom:\\', new Set([36])],
          ['Atom:b', new Set([26])],
          ['Atom:f', new Set([26])],
          ['Atom:n', new Set([26])],
          ['Atom:r', new Set([26])],
          ['Atom:t', new Set([26])],
          ['Atom:u', new Set([37])],
        ]),
        /* 29 */ new Map([['Atom:.', new Set([38])]]),
        /* 30 */ new Map([['Range:0-9', new Set([39])]]),
        /* 31 */ new Map([
          ['Atom:+', new Set([40])],
          ['Atom:-', new Set([40])],
          ['Range:0-9', new Set([41])],
        ]),
        /* 32 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Atom:a', new Set([42])],
          ['Range:b-z', new Set([18])],
        ]),
        /* 33 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-z', new Set([18])],
        ]),
        /* 34 */ new Map(),
        /* 35 */ new Map([
          ['Range:\t-\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -!', new Set([35])],
          ['Atom:"', new Set([43])],
          ['Range:#-[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 36 */ new Map([
          ['Atom:/', new Set([26])],
          ['Atom:\\', new Set([36])],
          ['Atom:b', new Set([26])],
          ['Atom:f', new Set([26])],
          ['Atom:n', new Set([26])],
          ['Atom:r', new Set([26])],
          ['Atom:t', new Set([26])],
          ['Atom:u', new Set([37])],
        ]),
        /* 37 */ new Map([
          ['Range:0-9', new Set([45])],
          ['Range:A-F', new Set([45])],
          ['Range:a-f', new Set([45])],
        ]),
        /* 38 */ new Map(),
        /* 39 */ new Map([
          ['Range:0-9', new Set([39])],
          ['Atom:E', new Set([31])],
          ['Atom:e', new Set([31])],
        ]),
        /* 40 */ new Map([['Range:0-9', new Set([41])]]),
        /* 41 */ new Map([['Range:0-9', new Set([41])]]),
        /* 42 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-f', new Set([18])],
          ['Atom:g', new Set([46])],
          ['Range:h-z', new Set([18])],
        ]),
        /* 43 */ new Map([
          ['Range:\t-\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -!', new Set([35])],
          ['Atom:"', new Set([47])],
          ['Range:#-[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 44 */ new Map([
          ['Range:\t-\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -!', new Set([35])],
          ['Atom:"', new Set([48])],
          ['Range:#-[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 45 */ new Map([
          ['Range:0-9', new Set([49])],
          ['Range:A-F', new Set([49])],
          ['Range:a-f', new Set([49])],
        ]),
        /* 46 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-l', new Set([18])],
          ['Atom:m', new Set([50])],
          ['Range:n-z', new Set([18])],
        ]),
        /* 47 */ new Map([
          ['Range:\t-\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -!', new Set([35])],
          ['Atom:"', new Set([51])],
          ['Range:#-[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 48 */ new Map([
          ['Range:\t-\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -!', new Set([35])],
          ['Atom:"', new Set([52])],
          ['Range:#-[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 49 */ new Map([
          ['Range:0-9', new Set([53])],
          ['Range:A-F', new Set([53])],
          ['Range:a-f', new Set([53])],
        ]),
        /* 50 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-d', new Set([18])],
          ['Atom:e', new Set([54])],
          ['Range:f-z', new Set([18])],
        ]),
        /* 51 */ new Map(),
        /* 52 */ new Map([
          ['Atom:\n', new Set([35])],
          ['Atom:\r', new Set([35])],
          ['Range: -[', new Set([35])],
          ['Atom:\\', new Set([44])],
          ['Range:]-\uffff', new Set([35])],
        ]),
        /* 53 */ new Map([
          ['Range:0-9', new Set([26])],
          ['Range:A-F', new Set([26])],
          ['Range:a-f', new Set([26])],
        ]),
        /* 54 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-m', new Set([18])],
          ['Atom:n', new Set([55])],
          ['Range:o-z', new Set([18])],
        ]),
        /* 55 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-s', new Set([18])],
          ['Atom:t', new Set([56])],
          ['Range:u-z', new Set([18])],
        ]),
        /* 56 */ new Map([
          ['Range:0-9', new Set([18])],
          ['Range:A-Z', new Set([18])],
          ['Atom:_', new Set([18])],
          ['Range:a-z', new Set([18])],
        ]),
      ],
      labels: [
        /* 0 */ undefined,
        /* 1 */ new Set(['IGNORED']),
        /* 2 */ new Set(['IGNORED']),
        /* 3 */ new Set(['IGNORED']),
        /* 4 */ new Set(['BANG']),
        /* 5 */ undefined,
        /* 6 */ new Set(['IGNORED']),
        /* 7 */ new Set(['DOLLAR']),
        /* 8 */ new Set(['AMPERSAND']),
        /* 9 */ new Set(['OPENING_PAREN']),
        /* 10 */ new Set(['CLOSING_PAREN']),
        /* 11 */ undefined,
        /* 12 */ undefined,
        /* 13 */ new Set(['NUMBER']),
        /* 14 */ new Set(['NUMBER']),
        /* 15 */ new Set(['COLON']),
        /* 16 */ new Set(['EQUALS']),
        /* 17 */ new Set(['AT']),
        /* 18 */ new Set(['NAME']),
        /* 19 */ new Set(['OPENING_BRACKET']),
        /* 20 */ new Set(['CLOSING_BRACKET']),
        /* 21 */ new Set(['NAME']),
        /* 22 */ new Set(['NAME']),
        /* 23 */ new Set(['OPENING_BRACE']),
        /* 24 */ new Set(['BAR']),
        /* 25 */ new Set(['CLOSING_BRACE']),
        /* 26 */ undefined,
        /* 27 */ new Set(['STRING_VALUE']),
        /* 28 */ undefined,
        /* 29 */ undefined,
        /* 30 */ undefined,
        /* 31 */ undefined,
        /* 32 */ new Set(['NAME']),
        /* 33 */ new Set(['ON', 'NAME']),
        /* 34 */ new Set(['STRING_VALUE']),
        /* 35 */ undefined,
        /* 36 */ undefined,
        /* 37 */ undefined,
        /* 38 */ new Set(['ELLIPSIS']),
        /* 39 */ new Set(['NUMBER']),
        /* 40 */ undefined,
        /* 41 */ new Set(['NUMBER']),
        /* 42 */ new Set(['NAME']),
        /* 43 */ undefined,
        /* 44 */ undefined,
        /* 45 */ undefined,
        /* 46 */ new Set(['NAME']),
        /* 47 */ undefined,
        /* 48 */ undefined,
        /* 49 */ undefined,
        /* 50 */ new Set(['NAME']),
        /* 51 */ new Set(['BLOCK_STRING_VALUE']),
        /* 52 */ undefined,
        /* 53 */ undefined,
        /* 54 */ new Set(['NAME']),
        /* 55 */ new Set(['NAME']),
        /* 56 */ new Set(['FRAGMENT', 'NAME']),
      ],
    });
  });
});
