name: masochist

services:
  app:
    user: "${APP_UID}:${APP_GID}"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    volumes:
      - /srv/masochist/repo:/srv/content:ro
      - /srv/masochist/public:/var/www/public:ro

  web:
    ports:
      - "80:80"
      - "443:443"
    environment:
      SITE_ADDRESS: "wincent.dev"
      TLS_CONFIG: ""
    volumes:
      - /srv/masochist/public:/var/www/public:ro
      - /srv/masochist/ops/Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/masochist/ops/Caddyfile.redirects:/etc/caddy/conf.d/redirects.caddy:ro
      - /etc/caddy/includes:/etc/caddy/includes:ro
